# Generated by Django 5.0.4 on 2024-04-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
        ('Stadium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.stadium'),
        ),
    ]
