# Generated by Django 5.0.4 on 2024-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M'),
        ),
    ]
