# Generated by Django 5.0.4 on 2024-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stadium', '0003_alter_stadium_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
